### ISSUE TITLE
Add personal characteristics to each AI agent

### ISSUE THREAD

**Issue by AndyTechGuy** [Terasology/MetalRenegades#45]
With the factions system introduced in #36, each character in an individual city shares a common character model. This can make the citizens look rather plain in a group, therefore some distinguishing characteristics should be included in the spawn process, like below:

- [x] A name for each citizen, like what is already done for cities. #74 
- [x] Variations in character size, easily done with the `scale` property inside the `skeletalmesh` of a character prefab. #74 
- [ ] Personality traits for each character which manipulate some behaviors, for example a _lazy_ character would move slower, a _greedy_ character would get hungry faster, etc.
- [x] ~~Slight colour/tone variations between characters.~~ Attempted as part of #74, didn't look good.

**Comment by jdrueckert** [comment]
@AndyTechGuy Guess after your second year of GSoC that's been resolved? :grin:
